[package]
name = "arena_gunpowder_and_sorcery"
version = "0.1.0"
authors = ["Chris Hamons <chris.hamons@gmail.com>"]
edition = "2018"
build = "build.rs"

[dependencies]
specs = "0.16.1"
specs-derive = "0.4.1"
num_enum = "0.5.0"
enum-iterator = "0.6.0"
num = "0.3.0"
num-traits = "0.2"
num-derive = "0.3"

[dependencies.sdl2]
version = "0.32.1"
default-features = false
features = ["image", "unsafe_textures"]