[package]
name = "arena_gunpowder_and_sorcery"
version = "0.1.0"
authors = ["Chris Hamons <chris.hamons@gmail.com>"]
edition = "2018"
build = "build.rs"

[features]
self_play = []
profile_self_play = ["self_play"]
image_tester = []
debug_text_alignmnet = []
default = []

[dependencies]
specs = {  version = "0.16.1", features = ["serde"] }
specs-derive = "0.4.1"
num_enum = "0.5.0"
enum-iterator = "0.6.0"
num-traits = "0.2"
num-derive = "0.3"
derive_is_enum_variant = "0.1.1"
serde = { version = "1.0.114", features = ["derive"] }
bincode = "1.3.1"
serde_json = "1.0.57"
rand = "0.7.3"
lazy_static = "1.4.0"
line_drawing = "0.8.0"
ordered-float = "2.0.0"
assert_approx_eq = "1.1.0"
leak = "0.1.2"
bitflags = "1.2.1"
regex = "1.3.9"

[dependencies.sdl2]
version = "0.32.1"
default-features = false
features = ["image", "ttf", "unsafe_textures"]