[package]
name = "arena_gunpowder_and_sorcery"
version = "0.1.0"
authors = ["Chris Hamons <chris.hamons@gmail.com>"]
edition = "2018"
build = "build.rs"

[dependencies]
tiled = "0.9.1"

[dependencies.sdl2]
version = "0.32.1"
default-features = false
features = ["image", "unsafe_textures"]